/**
 * write config data to src/js/environment-config.js
 */

var gulp = require('gulp'),
	opts = require('../opts'),
	packages = require('../packages'),
	plugins = require('../plugins'),
	utils = require('../utils');

gulp.task('app-config', function(done){

	utils.logMsg('\n*****' + 'begin app-config' + '*****\n');

	var dest = process.env.buildDirectory;

	var str = '//auto-generated by gulp from config.js\n';
	str += 'App.constant("environment", ' + JSON.stringify(opts.config) + ');';
	opts.fs.writeFile(opts.paths.src + opts.paths.jsDir + '/environment-config.js', str, function(err){
		if(err) throw err;
		utils.logMsg('\nconfig file write completed\n');
		done();
	});
});